import 'package:flutter/material.dart';
import '../../models/waste_record_model.dart';
import '../../services/waste_service.dart';

class WasteEntryScreen extends StatefulWidget {
  final String routeId;
  final WasteRecord? wasteRecord;
  final String wasteCollector;

  WasteEntryScreen(
      {required this.routeId, this.wasteRecord, required this.wasteCollector});

  @override
  _WasteEntryScreenState createState() => _WasteEntryScreenState();
}

class _WasteEntryScreenState extends State<WasteEntryScreen> {
  final _formKey = GlobalKey<FormState>();
  String _wasteType = '';
  double _weight = 0.0;

  @override
  Widget build(BuildContext context) {
    String wasteCollector = widget.wasteCollector; // Use passed wasteCollector

    return Scaffold(
      appBar: AppBar(
        title: Text('Waste Entry'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: InputDecoration(labelText: 'Waste Type'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a waste type';
                  }
                  return null;
                },
                onChanged: (value) {
                  _wasteType = value;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Weight (kg)'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a weight';
                  }
                  return null;
                },
                onChanged: (value) {
                  _weight = double.tryParse(value) ?? 0.0;
                },
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: () async {
                  if (_formKey.currentState!.validate()) {
                    // Create a new waste record
                    WasteRecord newRecord = WasteRecord(
                      id: '', // ID generated by Firestore
                      wasteType: _wasteType,
                      weight: _weight,
                      wasteCollector: wasteCollector,
                    );
                  }
                },
                child: Text('Submit'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
